// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE4WhfZmyt_d3qQ3IkZis9QYlZnZnNQQA',
    appId: '1:1098008945370:web:92e3127e770ee325a97be3',
    messagingSenderId: '1098008945370',
    projectId: 'catalogodepelicu',
    authDomain: 'catalogodepelicu.firebaseapp.com',
    storageBucket: 'catalogodepelicu.firebasestorage.app',
    measurementId: 'G-MFERWYNYLQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKaoxhP-kFPMEoeeLY3LnFhXh2Vb172bA',
    appId: '1:1098008945370:android:c6a91b38847e20d8a97be3',
    messagingSenderId: '1098008945370',
    projectId: 'catalogodepelicu',
    storageBucket: 'catalogodepelicu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYjNi6Mxar2KQc_NmEKlMnhzhjYpoJ2H0',
    appId: '1:1098008945370:ios:e04598ba0ec36e8ca97be3',
    messagingSenderId: '1098008945370',
    projectId: 'catalogodepelicu',
    storageBucket: 'catalogodepelicu.firebasestorage.app',
    iosBundleId: 'com.example.catalogodepeliculas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYjNi6Mxar2KQc_NmEKlMnhzhjYpoJ2H0',
    appId: '1:1098008945370:ios:e04598ba0ec36e8ca97be3',
    messagingSenderId: '1098008945370',
    projectId: 'catalogodepelicu',
    storageBucket: 'catalogodepelicu.firebasestorage.app',
    iosBundleId: 'com.example.catalogodepeliculas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE4WhfZmyt_d3qQ3IkZis9QYlZnZnNQQA',
    appId: '1:1098008945370:web:d9191f93397d66bfa97be3',
    messagingSenderId: '1098008945370',
    projectId: 'catalogodepelicu',
    authDomain: 'catalogodepelicu.firebaseapp.com',
    storageBucket: 'catalogodepelicu.firebasestorage.app',
    measurementId: 'G-NR2L0B7T3W',
  );
}
